# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Date of last logged in user.', null=True, verbose_name='Last Login'),
        ),
    ]
