# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Email that will be used as username.', max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(help_text='Full user name.', max_length=150, verbose_name='Name')),
                ('institution', models.CharField(blank=True, help_text='University or School in which the user is inserted.', max_length=100, verbose_name='Institution')),
                ('photo', models.ImageField(blank=True, help_text='Photo of user.', null=True, upload_to='user', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, help_text='Verify if the user is active.', verbose_name='Is Active?')),
                ('is_staff', models.BooleanField(default=False, help_text='Verify if the user is a staff.', verbose_name='Is Staff?')),
                ('is_teacher', models.BooleanField(default=False, help_text='Verify if the user is a teacher or a student.', verbose_name='Is Teacher?')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last moment the user logged in.', null=True, verbose_name='Last Login')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the user is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the user is updated.', verbose_name='Updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
    ]
