# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170727_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of user.', null=True, upload_to='static/accounts', verbose_name='Photo'),
        ),
    ]
