# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of user.', null=True, upload_to='accounts', verbose_name='Photo'),
        ),
    ]
