# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 23:20
from __future__ import unicode_literals

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20170829_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='student_limit',
            field=models.IntegerField(help_text='Maximum number of students in the class', validators=[classroom.models.min_value_validated], verbose_name='Student Limit'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, to='accounts.Student'),
        ),
    ]
