run:
	python3 manage.py runserver 0.0.0.0:8080

migrations:
	python3 manage.py makemigrations

migrate:
	python3 manage.py migrate

superuser:
	python3 manage.py createsuperuser

shell:
	python3 manage.py shell
