# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170730_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='news', to='core.Tag'),
        ),
    ]
